<?php
/**
 * ACF fields for the project post type
 *
 * @package    Korey_One
 * @subpackage Includes
 * @category   Fields
 * @since      1.0.0
 */

 namespace KoreyOne\Fields\Front_Sections;

 // Restrict direct access.
 if ( ! defined( 'ABSPATH' ) ) {
	 die;
 }

/**
 * Execute functions
 *
 * @since  1.0.0
 * @return void
 */
function setup() {

	// Return namespaced function.
	$ns = function( $function ) {
		return __NAMESPACE__ . "\\$function";
	};

	add_action( 'acf/init', $ns( 'fields' ) );
}

/**
 * ACF field group
 *
 * @since  1.0.0
 * @return void
 */
function fields() {

	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( [
		'key'    => 'group_61e47eb55a1e2',
		'title'  => 'Front Page Sections',
		'fields' => [
			[
				'key'               => 'field_61e47f200fee1',
				'label'             => 'Intro Slides',
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement'     => 'top',
				'endpoint'      => 0,
				'no_preference' => 0,
				'acfe_field_group_condition' => 0,
			],
			array(
				'key' => 'field_61e4846832970',
				'label' => 'Title Override',
				'name' => 'intro_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Override the site title in the slideshow overlay. Allowed HTML is <code>&lt;span&gt;</code>, <code>&lt;br&gt;</code>, <code>&lt;em&gt;</code>, & <code>&lt;strong&gt;</code>.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'acfe_field_group_condition' => 0,
			),
			array(
				'key' => 'field_61e484c432971',
				'label' => 'Desctiption Override',
				'name' => 'intro_description',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => 'Override the site description in the slideshow overlay. Allowed HTML is <code>&lt;span&gt;</code>, <code>&lt;br&gt;</code>, <code>&lt;em&gt;</code>, & <code>&lt;strong&gt;</code>.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => '',
				'acfe_textarea_code' => 0,
				'acfe_field_group_condition' => 0,
			),
			array(
				'key' => 'field_61e4850d13620',
				'label' => 'Overlay Color',
				'name' => 'intro_overlay_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 1,
				'return_format' => 'array',
				'display' => 'default',
				'button_label' => 'Select Color',
				'color_picker' => 1,
				'absolute' => 0,
				'input' => 1,
				'allow_null' => 1,
				'theme_colors' => 0,
				'colors' => array(
					'#000000' => 'Black',
					'#333333' => 'Charcoal',
					'#ffffff' => 'White',
				),
				'acfe_field_group_condition' => 0,
			),
			array(
				'key' => 'field_61e48686fb08c',
				'label' => 'Overlay Text Color',
				'name' => 'intro_overlay_text_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '34',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#ffffff',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'display' => 'default',
				'button_label' => 'Select Color',
				'color_picker' => 1,
				'absolute' => 0,
				'input' => 1,
				'allow_null' => 1,
				'theme_colors' => 0,
				'colors' => array(
					'#ffffff' => 'White',
					'#000000' => 'Black',
					'#333333' => 'Charcoal',
				),
				'acfe_field_group_condition' => 0,
			),
			array(
				'key' => 'field_61e47f350fee2',
				'label' => 'Intro Slides',
				'name' => 'intro_slides',
				'aria-label' => '',
				'type' => 'gallery',
				'instructions' => 'Minimum of 1280px wide by 720px high. Drag & drop images to set the order of appearance. If only one image is added then it will appear as a static background with no animation.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'insert' => 'append',
				'library' => 'all',
				'min' => '',
				'max' => '',
				'min_width' => 1280,
				'min_height' => 720,
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'acfe_field_group_condition' => 0,
			),
			array(
				'key' => 'field_61e47fb315bc8',
				'label' => 'Sections',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'no_preference' => 0,
				'acfe_field_group_condition' => 0,
			),
			array(
				'key' => 'field_61e47fd815bc9',
				'label' => 'Front Page Sections',
				'name' => 'front_sections',
				'aria-label' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => 'front-row-sections',
				),
				'acfe_field_group_condition' => 0,
				'required_message' => '',
				'acfe_flexible_advanced' => 1,
				'acfe_flexible_stylised_button' => 1,
				'acfe_flexible_layouts_templates' => 1,
				'acfe_flexible_layouts_previews' => 0,
				'acfe_flexible_layouts_placeholder' => 1,
				'acfe_flexible_layouts_thumbnails' => 0,
				'acfe_flexible_layouts_settings' => 0,
				'acfe_flexible_layouts_locations' => 0,
				'acfe_flexible_async' => array(
				),
				'acfe_flexible_add_actions' => array(
					0 => 'title',
					1 => 'close',
				),
				'acfe_flexible_remove_button' => array(
				),
				'acfe_flexible_modal_edit' => array(
					'acfe_flexible_modal_edit_enabled' => '1',
					'acfe_flexible_modal_edit_size' => 'large',
				),
				'acfe_flexible_modal' => array(
					'acfe_flexible_modal_enabled' => '0',
					'acfe_flexible_modal_title' => false,
					'acfe_flexible_modal_size' => 'full',
					'acfe_flexible_modal_col' => '4',
					'acfe_flexible_modal_categories' => false,
				),
				'acfe_flexible_grid' => array(
					'acfe_flexible_grid_enabled' => '1',
					'acfe_flexible_grid_align' => 'left',
					'acfe_flexible_grid_valign' => 'top',
					'acfe_flexible_grid_wrap' => '1',
				),
				'acfe_flexible_grid_container' => '',
				'layouts' => array(
					'layout_61e47feec47b7' => array(
						'key' => 'layout_61e47feec47b7',
						'name' => 'front_project_grid',
						'label' => 'Project Grid',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61e4803b15bca',
								'label' => 'Section Heading',
								'name' => 'front_section_heading',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e7ba9fdda8e',
								'label' => 'Menu Text',
								'name' => 'front_section_menu',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Text for the link to this section in the navigation menu.',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e8dafc1cb62',
								'label' => 'Project Category',
								'name' => 'front_grid_taxonomy',
								'aria-label' => '',
								'type' => 'button_group',
								'instructions' => 'Select how to categorize the projects in this grid.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'type' => 'Project Type',
									'role' => 'Project Role',
								),
								'allow_null' => 0,
								'default_value' => 'type',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e48333cdb6c',
								'label' => 'Project Types',
								'name' => 'front_grid_types',
								'aria-label' => '',
								'type' => 'acfe_taxonomy_terms',
								'instructions' => 'Select projects to display in this section by project type or your role in the project.',
								'required' => 1,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_61e8dafc1cb62',
											'operator' => '==',
											'value' => 'type',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'taxonomy' => array(
									0 => 'project_type',
								),
								'allow_terms' => '',
								'allow_level' => '',
								'field_type' => 'checkbox',
								'min' => '',
								'max' => '',
								'default_value' => array(
								),
								'return_format' => 'object',
								'layout' => 'horizontal',
								'toggle' => 1,
								'save_terms' => 0,
								'load_terms' => 0,
								'acfe_field_group_condition' => 0,
								'choices' => array(
								),
								'ui' => 0,
								'multiple' => 0,
								'allow_null' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'search_placeholder' => '',
								'allow_custom' => 0,
								'other_choice' => 0,
							),
							array(
								'key' => 'field_61e8daa01cb61',
								'label' => 'Project Roles',
								'name' => 'front_grid_roles',
								'aria-label' => '',
								'type' => 'acfe_taxonomy_terms',
								'instructions' => 'Select projects to display in this section by your role in the project.',
								'required' => 1,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_61e8dafc1cb62',
											'operator' => '==',
											'value' => 'role',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'taxonomy' => array(
									0 => 'project_role',
								),
								'allow_terms' => '',
								'allow_level' => '',
								'field_type' => 'checkbox',
								'min' => '',
								'max' => '',
								'default_value' => array(
								),
								'return_format' => 'object',
								'layout' => 'horizontal',
								'toggle' => 1,
								'save_terms' => 0,
								'load_terms' => 0,
								'acfe_field_group_condition' => 0,
								'choices' => array(
								),
								'ui' => 0,
								'multiple' => 0,
								'allow_null' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'search_placeholder' => '',
								'allow_custom' => 0,
								'other_choice' => 0,
							),
							array(
								'key' => 'field_61e481ac4491a',
								'label' => 'Number of Projects',
								'name' => 'front_grid_number',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => 'Select the maximum number of projects to show in this section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => 8,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f351f67eb31',
								'label' => 'Grid Columns',
								'name' => 'front_grid_columns',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => 'Select how many columns to display across the grid of projects. This does not affect mobile screens. Minimum of 3 columns, maximum of 6 columns.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => 4,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 3,
								'max' => 6,
								'step' => 1,
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e4825e4491b',
								'label' => 'Featured Images',
								'name' => 'front_grid_images',
								'aria-label' => '',
								'type' => 'button_group',
								'instructions' => 'Select the type of images to show for projects in this section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'poster' => 'Poster',
									'screenshot' => 'Screenshot',
								),
								'allow_null' => 0,
								'default_value' => 'poster',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'acfe_field_group_condition' => 0,
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => '',
						'acfe_flexible_render_style' => '',
						'acfe_flexible_render_script' => '',
						'acfe_flexible_modal_edit_size' => '',
						'acfe_layout_col' => 'auto',
						'acfe_layout_allowed_col' => '',
						'acfe_flexible_thumbnail' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_layout_locations' => array(
						),
						'acfe_flexible_category' => false,
					),
					'layout_61e870481199e' => array(
						'key' => 'layout_61e870481199e',
						'name' => 'front_contact_form',
						'label' => 'Contact Form',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61e8708b1199f',
								'label' => 'Section Heading',
								'name' => 'front_section_heading',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e870b7119a0',
								'label' => 'Menu Text',
								'name' => 'front_section_menu',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Text for the link to this section in the navigation menu.',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e870e814a04',
								'label' => 'Form Shortcode',
								'name' => 'front_form_shortcode',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Paste in the shortcode provided by the form plugin.',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e87161a17df',
								'label' => 'Content Before Form',
								'name' => 'front_form_content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => 'Optional content to precede the form fields.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
								'acfe_wysiwyg_height' => 300,
								'acfe_wysiwyg_max_height' => '',
								'acfe_wysiwyg_valid_elements' => '',
								'acfe_wysiwyg_custom_style' => '',
								'acfe_wysiwyg_disable_wp_style' => 0,
								'acfe_wysiwyg_autoresize' => 0,
								'acfe_wysiwyg_disable_resize' => 0,
								'acfe_wysiwyg_remove_path' => 0,
								'acfe_wysiwyg_menubar' => 0,
								'acfe_wysiwyg_transparent' => 0,
								'acfe_wysiwyg_merge_toolbar' => 0,
								'acfe_wysiwyg_custom_toolbar' => 0,
								'acfe_field_group_condition' => 0,
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => '',
						'acfe_flexible_render_style' => '',
						'acfe_flexible_render_script' => '',
						'acfe_flexible_modal_edit_size' => '',
						'acfe_layout_col' => 'auto',
						'acfe_layout_allowed_col' => '',
						'acfe_flexible_thumbnail' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_layout_locations' => array(
						),
						'acfe_flexible_category' => false,
					),
					'layout_61e87d2abff1a' => array(
						'key' => 'layout_61e87d2abff1a',
						'name' => 'front_image_gallery',
						'label' => 'Image Gallery',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61e87d42bff1b',
								'label' => 'Section Heading',
								'name' => 'front_section_heading',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e87d50bff1c',
								'label' => 'Menu Text',
								'name' => 'front_section_menu',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Text for the link to this section in the navigation menu.',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e87d8bbff1d',
								'label' => 'Content Before Gallery',
								'name' => 'front_gallery_content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
								'acfe_wysiwyg_height' => 300,
								'acfe_wysiwyg_max_height' => '',
								'acfe_wysiwyg_valid_elements' => '',
								'acfe_wysiwyg_custom_style' => '',
								'acfe_wysiwyg_disable_wp_style' => 0,
								'acfe_wysiwyg_autoresize' => 0,
								'acfe_wysiwyg_disable_resize' => 0,
								'acfe_wysiwyg_remove_path' => 0,
								'acfe_wysiwyg_menubar' => 0,
								'acfe_wysiwyg_transparent' => 0,
								'acfe_wysiwyg_merge_toolbar' => 0,
								'acfe_wysiwyg_custom_toolbar' => 0,
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61e87db5bff1e',
								'label' => 'Aspect Ratio',
								'name' => 'front_gallery_size',
								'aria-label' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'large-thumbnail' => '1:1 Square',
									'medium' => '3:2 Classic Film',
									'medium-video' => '16:9 HD Video',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'medium',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'acfe_field_group_condition' => 0,
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_61e87e60bff1f',
								'label' => 'Image Gallery',
								'name' => 'front_gallery',
								'aria-label' => '',
								'type' => 'gallery',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'insert' => 'append',
								'library' => 'all',
								'min' => '',
								'max' => '',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
								'acfe_field_group_condition' => 0,
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => '',
						'acfe_flexible_render_style' => '',
						'acfe_flexible_render_script' => '',
						'acfe_flexible_modal_edit_size' => '',
						'acfe_layout_col' => 'auto',
						'acfe_layout_allowed_col' => '',
						'acfe_flexible_thumbnail' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_layout_locations' => array(
						),
						'acfe_flexible_category' => false,
					),
					'layout_61f4775a6a237' => array(
						'key' => 'layout_61f4775a6a237',
						'name' => 'front_content_block',
						'label' => 'Content Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61f4779f6a238',
								'label' => 'Section Heading',
								'name' => 'front_section_heading',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_field_group_condition' => 0,
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_61f477b46a239',
								'label' => 'Menu Text',
								'name' => 'front_section_menu',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Text for the link to this section in the navigation menu.',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f477cb6a23a',
								'label' => 'Content',
								'name' => 'front_section_content',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
								'acfe_wysiwyg_height' => 300,
								'acfe_wysiwyg_max_height' => '',
								'acfe_wysiwyg_valid_elements' => '',
								'acfe_wysiwyg_custom_style' => '',
								'acfe_wysiwyg_disable_wp_style' => 0,
								'acfe_wysiwyg_autoresize' => 0,
								'acfe_wysiwyg_disable_resize' => 0,
								'acfe_wysiwyg_remove_path' => 0,
								'acfe_wysiwyg_menubar' => 0,
								'acfe_wysiwyg_transparent' => 0,
								'acfe_wysiwyg_merge_toolbar' => 0,
								'acfe_wysiwyg_custom_toolbar' => 0,
								'acfe_field_group_condition' => 0,
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => '',
						'acfe_flexible_render_style' => '',
						'acfe_flexible_render_script' => '',
						'acfe_flexible_modal_edit_size' => '',
						'acfe_layout_col' => 'auto',
						'acfe_layout_allowed_col' => '',
						'acfe_flexible_thumbnail' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_layout_locations' => array(
						),
						'acfe_flexible_category' => false,
					),
					'layout_61f9db7894d60' => array(
						'key' => 'layout_61f9db7894d60',
						'name' => 'front_resume',
						'label' => 'Resume',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61f9dbb994d61',
								'label' => 'Section Heading',
								'name' => 'front_section_heading',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f9dbf294d62',
								'label' => 'Menu Text',
								'name' => 'front_section_menu',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Text for the link to this section in the navigation menu.',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f9daf77a177',
								'label' => 'Resume',
								'name' => 'front_resume_type',
								'aria-label' => '',
								'type' => 'button_group',
								'instructions' => 'Select a method to provide a resume.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'file' => 'Upload File',
									'url' => 'Agency Link',
								),
								'allow_null' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f9daf77de88',
								'label' => 'Resume Link',
								'name' => 'front_resume_url',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => 'Paste the link to your resume.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_61f9daf77a177',
											'operator' => '==',
											'value' => 'url',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f9daf781b8c',
								'label' => 'Resume File',
								'name' => 'front_resume_file',
								'aria-label' => '',
								'type' => 'file',
								'instructions' => 'File will be uploaded to the Media Library',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_61f9daf77a177',
											'operator' => '==',
											'value' => 'file',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'uploader' => '',
								'return_format' => 'array',
								'min_size' => '',
								'max_size' => '',
								'mime_types' => '',
								'upload_folder' => '',
								'multiple' => 0,
								'max' => '',
								'acfe_field_group_condition' => 0,
								'library' => 'all',
							),
							array(
								'key' => 'field_61f9dd3430185',
								'label' => 'Resume Notice',
								'name' => 'front_resume_notice',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
								'acfe_wysiwyg_height' => 300,
								'acfe_wysiwyg_max_height' => '',
								'acfe_wysiwyg_valid_elements' => '',
								'acfe_wysiwyg_custom_style' => '',
								'acfe_wysiwyg_disable_wp_style' => 0,
								'acfe_wysiwyg_autoresize' => 0,
								'acfe_wysiwyg_disable_resize' => 0,
								'acfe_wysiwyg_remove_path' => 0,
								'acfe_wysiwyg_menubar' => 0,
								'acfe_wysiwyg_transparent' => 0,
								'acfe_wysiwyg_merge_toolbar' => 0,
								'acfe_wysiwyg_custom_toolbar' => 0,
								'acfe_field_group_condition' => 0,
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => '',
						'acfe_flexible_render_style' => '',
						'acfe_flexible_render_script' => '',
						'acfe_flexible_modal_edit_size' => '',
						'acfe_layout_col' => 'auto',
						'acfe_layout_allowed_col' => '',
						'acfe_flexible_thumbnail' => false,
						'acfe_flexible_settings' => false,
						'acfe_flexible_settings_size' => 'medium',
						'acfe_layout_locations' => array(
						),
						'acfe_flexible_category' => false,
					),
					'layout_61f9e5ecfc7ae' => array(
						'key' => 'layout_61f9e5ecfc7ae',
						'name' => 'front_agents',
						'label' => 'Representation',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_61f9e622fc7af',
								'label' => 'Section Heading',
								'name' => 'front_section_heading',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f9e631fc7b0',
								'label' => 'Menu Text',
								'name' => 'front_section_menu',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'Text for the link to this section in the navigation menu.',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'required_message' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f9e21279356',
								'label' => 'Representation Notice',
								'name' => 'front_agents_notice',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
								'acfe_wysiwyg_height' => 300,
								'acfe_wysiwyg_max_height' => '',
								'acfe_wysiwyg_valid_elements' => '',
								'acfe_wysiwyg_custom_style' => '',
								'acfe_wysiwyg_disable_wp_style' => 0,
								'acfe_wysiwyg_autoresize' => 0,
								'acfe_wysiwyg_disable_resize' => 0,
								'acfe_wysiwyg_remove_path' => 0,
								'acfe_wysiwyg_menubar' => 0,
								'acfe_wysiwyg_transparent' => 0,
								'acfe_wysiwyg_merge_toolbar' => 0,
								'acfe_wysiwyg_custom_toolbar' => 0,
								'acfe_field_group_condition' => 0,
							),
							array(
								'key' => 'field_61f9e2127c2a1',
								'label' => 'Departments',
								'name' => 'front_agent_departments',
								'aria-label' => '',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'acfe_field_group_condition' => 0,
								'required_message' => '',
								'acfe_repeater_stylised_button' => 1,
								'layout' => 'block',
								'min' => 0,
								'max' => 0,
								'collapsed' => 'field_61f9e2138de31',
								'button_label' => 'Add Department',
								'rows_per_page' => 20,
								'sub_fields' => array(
									array(
										'key' => 'field_61f9e2138de31',
										'label' => 'Department Name',
										'name' => 'front_agent_dept_name',
										'aria-label' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'required_message' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
										'acfe_field_group_condition' => 0,
										'parent_repeater' => 'field_61f9e2127c2a1',
									),
									array(
										'key' => 'field_61f9e21391162',
										'label' => 'Agents',
										'name' => 'front_agents',
										'aria-label' => '',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'acfe_repeater_stylised_button' => 0,
										'collapsed' => 'field_61f9e213b36d0',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Agent',
										'acfe_field_group_condition' => 0,
										'rows_per_page' => 20,
										'parent_repeater' => 'field_61f9e2127c2a1',
										'sub_fields' => array(
											array(
												'key' => 'field_61f9e213b36d0',
												'label' => 'Name',
												'name' => 'front_agent_name',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
												'acfe_field_group_condition' => 0,
												'parent_repeater' => 'field_61f9e21391162',
											),
											array(
												'key' => 'field_61f9e213b6dc2',
												'label' => 'Agency',
												'name' => 'front_agent_agency',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
												'acfe_field_group_condition' => 0,
												'parent_repeater' => 'field_61f9e21391162',
											),
											array(
												'key' => 'field_61f9e213ba96a',
												'label' => 'Phone',
												'name' => 'front_agent_phone',
												'aria-label' => '',
												'type' => 'text',
												'instructions' => 'Use dashes only to make the number a link on mobile devices.',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'required_message' => '',
												'default_value' => '',
												'placeholder' => 'Format: 800-555-1212',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
												'acfe_field_group_condition' => 0,
												'parent_repeater' => 'field_61f9e21391162',
											),
											array(
												'key' => 'field_61f9e213be621',
												'label' => 'Email',
												'name' => 'front_agent_email',
												'aria-label' => '',
												'type' => 'email',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'required_message' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'acfe_field_group_condition' => 0,
												'parent_repeater' => 'field_61f9e21391162',
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
						'acfe_flexible_render_template' => '',
						'acfe_flexible_render_style'    => '',
						'acfe_flexible_render_script'   => '',
						'acfe_flexible_modal_edit_size' => '',
						'acfe_layout_col'               => 'auto',
						'acfe_layout_allowed_col'       => '',
						'acfe_flexible_thumbnail'       => false,
						'acfe_flexible_settings'        => false,
						'acfe_flexible_settings_size'   => 'medium',
						'acfe_layout_locations'         => [],
						'acfe_flexible_category'        => false,
					),
				),
				'min' => '',
				'max' => '',
				'button_label' => 'Add Section',
				'acfe_flexible_hide_empty_message' => false,
				'acfe_flexible_empty_message'      => '',
				'acfe_flexible_layouts_state'      => false,
			),
		],
		'location' => [
			[
				[
					'param'    => 'page_type',
					'operator' => '==',
					'value'    => 'front_page',
				],
				[
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => 'templates/front-page-sections.php',
				],
			],
		],
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => [
			0 => 'author',
			1 => 'block_editor',
			2 => 'comments',
			3 => 'the_content',
			4 => 'discussion',
			5 => 'format',
			6 => 'revisions',
			7 => 'send-trackbacks',
		],
		'active'             => true,
		'description'        => '',
		'show_in_rest'       => 0,
		'acfe_autosync'      => '',
		'acfe_form'          => 0,
		'acfe_display_title' => '',
		'acfe_meta'          => '',
		'acfe_note'          => '',
	] );
}
